{
  "comments": [
    {
      "robotId": "zuul",
      "robotRunId": "f99fd9e8d713470d8492cc9ae8784aa8",
      "url": "https://telecominfraproject.zuul.vexxhost.dev/buildset/f99fd9e8d713470d8492cc9ae8784aa8",
      "fixSuggestions": [],
      "key": {
        "uuid": "8746014f_3860b448",
        "filename": "gnpy/core/info.py",
        "patchSetId": 4
      },
      "lineNbr": 281,
      "author": {
        "id": 1017521
      },
      "writtenOn": "2021-08-12T16:39:08Z",
      "side": 1,
      "message": "linters-diff-ci: E128 continuation line under-indented for visual indent",
      "tag": "autogenerated:zuul:check",
      "revId": "1143d0106276d9f2964c42629dcefc68106bb833",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}